// Attachments, documents, pasting, and the breakdown that combines them.
// ---------------------------------------------------------------------------
// The behaviour under test is the one the analyzer used to get wrong in the most
// visible way: "Summarize this report" with a 40-page PDF attached reported nine
// tokens.
//
// Fixtures are real files, generated by test/fixtures/make-files.js — a
// hand-built PDF with Flate-compressed content streams, an uncompressed one, and
// a real PNG. Nothing here is mocked at the parsing layer, because the parsing
// is the part most likely to be wrong.

const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');

const DOCS = require('../lib/tokens/documents.js');
const TRACK = require('../lib/tokens/attachments.js');
const CTX = require('../lib/tokens/context.js');
const dom = require('./helpers/dom.js');

const FILES = path.join(__dirname, 'fixtures', 'files');

const CLAUDE = { provider: 'anthropic', canonicalModel: 'claude-opus-5', surface: 'claude-web' };
const CHATGPT = { provider: 'openai', canonicalModel: 'gpt-5.6-sol', surface: 'chatgpt' };

/** A File-alike backed by real bytes. `arrayBuffer` is what the code uses. */
function fileFrom(name, bytes, type) {
  const data = bytes instanceof Uint8Array ? bytes : new Uint8Array(Buffer.from(bytes));
  return {
    name,
    type: type || '',
    size: data.length,
    lastModified: 1755000000000,
    bytes: data,
    arrayBuffer: async () => data.buffer.slice(data.byteOffset, data.byteOffset + data.length),
  };
}

function fixture(name, type) {
  return fileFrom(name, new Uint8Array(fs.readFileSync(path.join(FILES, name))), type);
}

// ── Classification ─────────────────────────────────────────────────────────

test('files are classified by extension first, MIME second', () => {
  const kind = (name, type) => DOCS.classify({ name, type }).kind;
  assert.strictEqual(kind('notes.md'), 'text');
  assert.strictEqual(kind('data.csv'), 'text');
  assert.strictEqual(kind('config.json'), 'text');
  assert.strictEqual(kind('app.py'), 'text');
  assert.strictEqual(kind('index.tsx'), 'text');
  assert.strictEqual(kind('report.pdf'), 'pdf');
  assert.strictEqual(kind('chart.png'), 'image');
  assert.strictEqual(kind('deck.pptx'), 'opaque');
  assert.strictEqual(kind('archive.bin'), 'unknown');
  // Browsers report octet-stream for most source files; the extension must win.
  assert.strictEqual(kind('server.go', 'application/octet-stream'), 'text');
  // And a MIME type still rescues an extension we have never seen.
  assert.strictEqual(kind('README', 'text/plain'), 'text');
});

// ── Text files ─────────────────────────────────────────────────────────────

test('text files are read and tokenized in full, not guessed from byte size', async () => {
  const body = 'The quarterly summary covers every region.\n'.repeat(200);
  const record = await DOCS.analyze(fileFrom('notes.md', body), CLAUDE);
  assert.strictEqual(record.kind, 'text');
  assert.strictEqual(record.characters, body.length);
  assert.strictEqual(record.method, 'local-tokenizer');
  assert.ok(record.total > 1500, `expected thousands of tokens, got ${record.total}`);
});

test('the same text file costs different amounts on Claude and ChatGPT', async () => {
  const body = 'The quarterly summary covers every region and highlights the principal risks.\n'.repeat(120);
  const claude = await DOCS.analyze(fileFrom('notes.md', body), CLAUDE);
  const chatgpt = await DOCS.analyze(fileFrom('notes.md', body), CHATGPT);
  assert.ok(claude.total > chatgpt.total * 1.3,
    `Claude ${claude.total} vs ChatGPT ${chatgpt.total} — one generic estimator would make these equal`);
});

test('JSON and code files are counted as what they are', async () => {
  const json = JSON.stringify({ rows: Array.from({ length: 200 }, (_, i) => ({ id: i, name: `row-${i}`, ok: true })) });
  const record = await DOCS.analyze(fileFrom('rows.json', json, 'application/json'), CHATGPT);
  assert.strictEqual(record.kind, 'text');
  // Dense punctuation: JSON must not be counted at prose density.
  assert.ok(json.length / record.total < 3.5, `${(json.length / record.total).toFixed(2)} chars/token`);
});

// ── PDFs ───────────────────────────────────────────────────────────────────

test('a PDF’s page count is read from its structure', async () => {
  const parsed = await DOCS.parse(fixture('report-6p.pdf', 'application/pdf'));
  assert.strictEqual(parsed.pages, 6);
  assert.strictEqual(parsed.pagesKnown, true);
});

test('PDF text is extracted locally from Flate-compressed content streams', async () => {
  const parsed = await DOCS.parse(fixture('report-6p.pdf', 'application/pdf'));
  assert.strictEqual(parsed.extractionUsable, true, 'compressed streams must be inflated and read');
  assert.ok(parsed.text.includes('quarterly report'), 'the actual words, not a byte-size guess');
  assert.ok(parsed.chars > 1000, `only ${parsed.chars} characters extracted`);
});

test('uncompressed PDFs are read too', async () => {
  const parsed = await DOCS.parse(fixture('plain-3p.pdf', 'application/pdf'));
  assert.strictEqual(parsed.pages, 3);
  assert.strictEqual(parsed.extractionUsable, true);
});

test('a PDF is NOT treated as plain text — the visual half is reported separately', async () => {
  const record = await DOCS.analyze(fixture('report-6p.pdf', 'application/pdf'), CLAUDE, { surface: 'claude-web' });
  assert.ok(record.textTokens > 0, 'extracted text contributes');
  assert.ok(record.visualTokens > 0, 'and so does per-page document processing');
  assert.ok(record.visualTokens > record.textTokens,
    'Claude renders every page as an image; on a sparse document that dominates');
  assert.strictEqual(record.total, record.textTokens + record.visualTokens);
  assert.strictEqual(record.confidence, 'estimated', 'never claimed as exact');
  assert.match(record.detail, /image/i);
});

test('a PDF costs different amounts on Claude and ChatGPT', async () => {
  const parsed = await DOCS.parse(fixture('report-6p.pdf', 'application/pdf'));
  const claude = DOCS.cost(parsed, CLAUDE, { surface: 'claude-web' });
  const chatgpt = DOCS.cost(parsed, CHATGPT, { surface: 'chatgpt' });
  assert.notStrictEqual(claude.total, chatgpt.total);
  assert.match(chatgpt.detail, /visual retrieval/i,
    'ChatGPT’s page-image handling is conditional and must be described as such');
});

test('ChatGPT’s ~110k in-context cap is applied and explained', async () => {
  // A PDF large enough that ChatGPT would index most of it rather than stuff it.
  const parsed = {
    name: 'huge.pdf', kind: 'pdf', size: 40e6, pages: 900, pagesKnown: true,
    encrypted: false, chars: 2.4e6, extractionUsable: true,
    text: 'The quarterly summary covers every region. '.repeat(56000),
  };
  const record = DOCS.cost(parsed, CHATGPT, { surface: 'chatgpt' });
  assert.strictEqual(record.textTokens, 110000, 'capped at the documented limit');
  assert.ok(record.indexedOverflow > 0);
  assert.match(record.detail, /search index/i);
});

test('an unreadable PDF falls back to the documented per-page band, not to zero', async () => {
  // A structurally valid PDF whose pages carry no extractable text: a scan.
  const scan = Buffer.concat([
    Buffer.from('%PDF-1.7\n'),
    Buffer.from('1 0 obj\n<< /Type /Pages /Kids [2 0 R 3 0 R] /Count 2 >>\nendobj\n'),
    Buffer.from('2 0 obj\n<< /Type /Page /Parent 1 0 R >>\nendobj\n'),
    Buffer.from('3 0 obj\n<< /Type /Page /Parent 1 0 R >>\nendobj\n'),
    Buffer.from('trailer\n<< /Root 1 0 R >>\n%%EOF\n'),
  ]);
  const record = await DOCS.analyze(fileFrom('scan.pdf', new Uint8Array(scan), 'application/pdf'),
    CLAUDE, { surface: 'claude-web' });
  assert.strictEqual(record.pages, 2);
  assert.ok(record.textTokens >= 2 * 1500 && record.textTokens <= 2 * 3000,
    'Anthropic’s documented 1,500–3,000 tokens per page');
  assert.match(record.detail, /could not be extracted|per-page band/);
});

test('an encrypted PDF says so rather than reporting nothing', async () => {
  const enc = Buffer.from('%PDF-1.7\n1 0 obj\n<< /Type /Pages /Count 4 >>\nendobj\n'
    + 'trailer\n<< /Encrypt 9 0 R /Root 1 0 R >>\n%%EOF\n');
  const record = await DOCS.analyze(fileFrom('locked.pdf', new Uint8Array(enc), 'application/pdf'), CLAUDE);
  assert.ok(record.total > 0, 'four pages still cost something');
  assert.match(record.detail, /encrypted/i);
});

// ── Images ─────────────────────────────────────────────────────────────────

test('image dimensions are read from the file header', () => {
  const png = new Uint8Array(fs.readFileSync(path.join(FILES, 'chart-640x480.png')));
  assert.deepStrictEqual(DOCS.imageDimensions(png), { width: 640, height: 480 });
});

test('Claude image tokens reproduce every row of the published table', () => {
  // Anthropic's Vision docs, "Resolution and token cost". If this ever drifts,
  // the formula has stopped matching the provider and the estimate is wrong.
  const rows = [
    [200, 200, 64, 64],
    [1000, 1000, 1296, 1296],
    [1092, 1092, 1521, 1521],
    [1920, 1080, 1560, 2691],
    [2000, 1500, 1564, 3888],
    [3840, 2160, 1560, 4784],
  ];
  for (const [w, h, standard, high] of rows) {
    assert.strictEqual(DOCS.anthropicImageTokens(w, h, 'standard'), standard, `${w}x${h} standard`);
    assert.strictEqual(DOCS.anthropicImageTokens(w, h, 'high'), high, `${w}x${h} high-resolution`);
  }
});

test('current Claude models use the high-resolution tier, older ones do not', () => {
  assert.strictEqual(DOCS.anthropicTierFor('claude-opus-5'), 'high');
  assert.strictEqual(DOCS.anthropicTierFor('claude-opus-4-7'), 'high');
  assert.strictEqual(DOCS.anthropicTierFor('claude-haiku-4-5'), 'standard');
});

test('OpenAI images are a range, because GPT-5.6 may skip the patch budget', () => {
  const band = DOCS.openaiImageTokens(1800, 2400, {});
  assert.ok(band.low <= band.high);
  assert.strictEqual(band.low, 1536, 'the documented patch budget');
  assert.ok(band.high > band.low, 'and the uncapped original-detail count above it');
});

test('an image with unreadable dimensions gets a wide band, not a made-up number', async () => {
  const record = await DOCS.analyze(fileFrom('mystery.heic', new Uint8Array([1, 2, 3, 4]), 'image/heic'), CLAUDE);
  assert.strictEqual(record.confidence, 'estimated');
  assert.ok(record.high > record.low * 4, 'the uncertainty is visible in the band');
});

// ── Opaque documents ───────────────────────────────────────────────────────

test('a .docx is estimated from its size and labelled low confidence', async () => {
  const record = await DOCS.analyze(fileFrom('memo.docx', new Uint8Array(200000)), CLAUDE);
  assert.strictEqual(record.kind, 'opaque');
  assert.strictEqual(record.confidence, 'low');
  assert.ok(record.high > record.low, 'a band, not a figure');
  assert.match(record.detail, /estimated from/);
});

// ── The tracker: capture, sync, lifecycle ──────────────────────────────────

function makeTracker(page, target) {
  let current = target;
  const tracker = TRACK.createTracker({
    document: page.document,
    adapter: {
      composerSurfaceSelector: 'form[data-type="unified-composer"], #composer-background',
      attachmentSelectors: ['[data-testid="composer-file-chip"]'],
    },
    getTarget: () => current,
    getSurface: () => current.surface,
  });
  return { tracker, setTarget: (t) => { current = t; } };
}

/** Add a chip to the composer, the way the product renders one. */
function addChip(page, name) {
  const chip = page.document.createElement('div');
  chip.setAttribute('data-testid', 'composer-file-chip');
  chip.setAttribute('title', name);
  chip.textContent = name;
  page.document.getElementById('composer-background').appendChild(chip);
  return chip;
}

test('a file added through the picker is captured, parsed, and counted',
  { skip: !dom.available }, async () => {
    const page = dom.createPage(dom.CHATGPT_HTML);
    try {
      const { tracker } = makeTracker(page, CLAUDE);
      tracker.start();
      addChip(page, 'notes.md');
      tracker.noteFiles([fileFrom('notes.md', 'Summary line.\n'.repeat(300))], 'file-picker');
      const list = await tracker.settle();
      assert.strictEqual(list.length, 1);
      assert.strictEqual(list[0].name, 'notes.md');
      assert.ok(list[0].total > 500);
    } finally { page.restore(); }
  });

test('removing the chip removes the file from the count', { skip: !dom.available }, async () => {
  const page = dom.createPage(dom.CHATGPT_HTML);
  try {
    const { tracker } = makeTracker(page, CLAUDE);
    tracker.start();
    const chip = addChip(page, 'notes.md');
    tracker.noteFiles([fileFrom('notes.md', 'Summary line.\n'.repeat(300))], 'drop');
    // The composer's mutation observer would run this; called directly so the
    // test does not depend on a debounce.
    tracker.syncFromDom();
    assert.strictEqual((await tracker.settle()).length, 1);

    chip.remove();
    tracker.syncFromDom();
    assert.strictEqual(tracker.attachments().length, 0, 'the removed file must stop counting');
    assert.strictEqual(tracker.size, 0, 'and its bytes must stop being held');
  } finally { page.restore(); }
});

test('two files are both counted; removing one leaves the other', { skip: !dom.available }, async () => {
  const page = dom.createPage(dom.CHATGPT_HTML);
  try {
    const { tracker } = makeTracker(page, CLAUDE);
    tracker.start();
    const first = addChip(page, 'report-6p.pdf');
    addChip(page, 'plain-3p.pdf');
    tracker.noteFiles([
      fixture('report-6p.pdf', 'application/pdf'),
      fixture('plain-3p.pdf', 'application/pdf'),
    ], 'drop');
    tracker.syncFromDom();
    const both = await tracker.settle();
    assert.strictEqual(both.length, 2);
    const total = both.reduce((n, f) => n + f.total, 0);

    first.remove();
    tracker.syncFromDom();
    const one = tracker.attachments();
    assert.strictEqual(one.length, 1);
    assert.strictEqual(one[0].name, 'plain-3p.pdf');
    assert.ok(one[0].total < total, 'the total went down');
  } finally { page.restore(); }
});

test('a truncated chip name still matches the file it names', () => {
  assert.strictEqual(TRACK.namesMatch('annual-repo….pdf', 'annual-report-2026-final.pdf'), true);
  assert.strictEqual(TRACK.namesMatch('notes.md', 'notes.md'), true);
  assert.strictEqual(TRACK.namesMatch('budget.xlsx', 'notes.md'), false);
  assert.strictEqual(TRACK.namesMatch('report.pdf', 'report.md'), false, 'a different extension is a different file');
});

test('reset clears everything — a new chat is a new context', { skip: !dom.available }, async () => {
  const page = dom.createPage(dom.CHATGPT_HTML);
  try {
    const { tracker } = makeTracker(page, CLAUDE);
    tracker.start();
    addChip(page, 'notes.md');
    tracker.noteFiles([fileFrom('notes.md', 'x'.repeat(5000))], 'drop');
    assert.strictEqual((await tracker.settle()).length, 1);

    tracker.reset('navigation');
    assert.strictEqual(tracker.attachments().length, 0);
    assert.strictEqual(tracker.size, 0);
  } finally { page.restore(); }
});

test('a model switch re-costs from cache without re-reading the file',
  { skip: !dom.available }, async () => {
    const page = dom.createPage(dom.CHATGPT_HTML);
    try {
      const { tracker, setTarget } = makeTracker(page, CLAUDE);
      tracker.start();
      addChip(page, 'report-6p.pdf');

      // Count the reads. Parsing must happen exactly once per file, however many
      // times the model changes — re-inflating a PDF on every picker click is
      // what makes an extension feel broken.
      let reads = 0;
      const file = fixture('report-6p.pdf', 'application/pdf');
      const inner = file.arrayBuffer;
      file.arrayBuffer = async () => { reads += 1; return inner(); };

      tracker.noteFiles([file], 'drop');
      const asClaude = await tracker.settle();
      assert.strictEqual(reads, 1);

      setTarget(CHATGPT);
      const asChatGpt = tracker.attachments();
      assert.strictEqual(reads, 1, 'the file was not read again');
      assert.notStrictEqual(asChatGpt[0].total, asClaude[0].total,
        'but it was re-priced for the new provider');
    } finally { page.restore(); }
  });

test('a chip we never captured is listed, not silently dropped', { skip: !dom.available }, () => {
  const page = dom.createPage(dom.CHATGPT_HTML);
  try {
    const { tracker } = makeTracker(page, CLAUDE);
    tracker.start();
    addChip(page, 'restored-draft.pdf');       // attached before we were listening
    tracker.syncFromDom();
    const list = tracker.attachments();
    assert.strictEqual(list.length, 1);
    assert.strictEqual(list[0].unreadable, true);
    assert.strictEqual(list[0].total, 0, 'no invented number');
    assert.match(list[0].detail, /not included/);
  } finally { page.restore(); }
});

// ── The breakdown ──────────────────────────────────────────────────────────

function makeContext(target, tracker) {
  let current = target;
  const ctx = CTX.createContext({
    getTarget: () => current,
    getSurface: () => current.surface,
    tracker: tracker || null,
  });
  return { ctx, setTarget: (t) => { current = t; } };
}

test('typed text alone is one line and the whole total', () => {
  const { ctx } = makeContext(CHATGPT);
  const b = ctx.compose('Summarize the quarterly report and identify the top three risks.');
  assert.strictEqual(b.parts.length, 1);
  assert.strictEqual(b.parts[0].id, 'typed');
  assert.strictEqual(b.total, b.parts[0].tokens);
  assert.strictEqual(b.headlineLabel, 'User-supplied input');
});

test('pasted content is a SUBDIVISION of the composer, never an addition', () => {
  const { ctx } = makeContext(CHATGPT);
  const pasted = 'The quarterly summary covers every region and lists each risk. '.repeat(40);
  const typed = 'Summarize this and identify the risks.\n\n';
  ctx.notePaste(pasted);

  const b = ctx.compose(typed + pasted);
  const lines = Object.fromEntries(b.parts.map((p) => [p.id, p.tokens]));
  assert.ok(lines.pasted > 0, 'the paste is broken out');
  assert.ok(lines.typed > 0, 'and so is what was typed');
  // The load-bearing assertion: the parts sum to the composer's own count.
  const whole = require('../lib/tokens/counter.js').count(typed + pasted, CHATGPT);
  assert.strictEqual(lines.typed + lines.pasted, whole,
    'double counting would make this larger than the composer’s own total');
  assert.strictEqual(b.total, whole);
});

test('a paste the user then deletes stops being counted', () => {
  const { ctx } = makeContext(CHATGPT);
  const pasted = 'Deleted text. '.repeat(50);
  ctx.notePaste(pasted);
  assert.ok(ctx.compose(`Prompt. ${pasted}`).parts.some((p) => p.id === 'pasted'));

  const after = ctx.compose('Prompt only now, the paste is gone.');
  assert.ok(!after.parts.some((p) => p.id === 'pasted'));
  assert.strictEqual(ctx.pasteCount, 0, 'and it is forgotten, so it cannot come back');
});

test('a paste nested inside a larger paste is counted once', () => {
  const { ctx } = makeContext(CHATGPT);
  const inner = 'Inner block of pasted prose. '.repeat(30);
  const outer = `Wrapper start. ${inner} Wrapper end. ${'More outer text. '.repeat(30)}`;
  ctx.notePaste(inner);
  ctx.notePaste(outer);

  const b = ctx.compose(outer);
  const whole = require('../lib/tokens/counter.js').count(outer, CHATGPT);
  assert.strictEqual(b.total, whole, 'the overlapping runs must not both count');
});

test('short pastes are not broken out — pasting a URL is typing', () => {
  const { ctx } = makeContext(CHATGPT);
  assert.strictEqual(ctx.notePaste('https://example.com/report'), false);
  assert.strictEqual(ctx.compose('See https://example.com/report').parts.length, 1);
});

test('a huge paste is counted as the text it is, not as a flat allowance', () => {
  const { ctx } = makeContext(CHATGPT);
  const huge = Array.from({ length: 20000 }, (_, i) => `word${i % 500}`).join(' ');
  ctx.notePaste(huge);
  const b = ctx.compose(`Summarize this:\n\n${huge}`);
  assert.ok(b.total > 20000, `20,000 words must exceed 20,000 tokens, got ${b.total}`);
});

test('a short prompt with a big PDF reports the PDF, not nine tokens',
  { skip: !dom.available }, async () => {
    const page = dom.createPage(dom.CHATGPT_HTML);
    try {
      const { tracker } = makeTracker(page, CLAUDE);
      tracker.start();
      addChip(page, 'report-6p.pdf');
      tracker.noteFiles([fixture('report-6p.pdf', 'application/pdf')], 'drop');
      await tracker.settle();

      const { ctx } = makeContext(CLAUDE, tracker);
      const b = ctx.compose('Summarize this report and identify the risks');
      const typed = b.parts.find((p) => p.id === 'typed');
      assert.ok(typed.tokens < 30, 'the prompt really is tiny');
      assert.ok(b.total > 5000, `the request is not: ${b.total} tokens`);
      assert.strictEqual(b.headlineLabel, 'Observable input');
      assert.strictEqual(b.confidence, 'estimated');
    } finally { page.restore(); }
  });

test('prompt + pasted code + PDF + a model switch all flow through',
  { skip: !dom.available }, async () => {
    const page = dom.createPage(dom.CHATGPT_HTML);
    try {
      const { tracker, setTarget: setTrackerTarget } = makeTracker(page, CHATGPT);
      tracker.start();
      addChip(page, 'report-6p.pdf');
      tracker.noteFiles([fixture('report-6p.pdf', 'application/pdf')], 'drop');
      await tracker.settle();

      const { ctx, setTarget } = makeContext(CHATGPT, tracker);
      const code = 'function handle(req, res) {\n  return res.json({ ok: true, id: req.params.id });\n}\n'.repeat(40);
      ctx.notePaste(code);
      const composer = `Review this handler and the attached report.\n\n${code}`;

      const asChatGpt = ctx.compose(composer);
      assert.strictEqual(asChatGpt.parts.length, 3, 'typed, pasted, and the file');
      assert.ok(asChatGpt.parts.some((p) => p.id === 'pasted'));
      assert.ok(asChatGpt.parts.some((p) => p.kind === 'pdf'));

      setTarget(CLAUDE);
      setTrackerTarget(CLAUDE);
      const asClaude = ctx.compose(composer);
      assert.ok(asClaude.total > asChatGpt.total,
        `Claude ${asClaude.total} vs ChatGPT ${asChatGpt.total} — every line re-costs`);
      assert.strictEqual(asClaude.tokenizer, 'claude-4.7');
      assert.strictEqual(asChatGpt.tokenizer, 'o200k_base');
    } finally { page.restore(); }
  });

test('confidence is decided by the weakest part', { skip: !dom.available }, async () => {
  const page = dom.createPage(dom.CHATGPT_HTML);
  try {
    const { tracker } = makeTracker(page, CLAUDE);
    tracker.start();

    const textOnly = makeContext(CLAUDE, tracker).ctx.compose('A prompt with no attachments at all here.');
    assert.strictEqual(textOnly.confidence, 'high');

    addChip(page, 'memo.docx');
    tracker.noteFiles([fileFrom('memo.docx', new Uint8Array(120000))], 'drop');
    await tracker.settle();
    const withDocx = makeContext(CLAUDE, tracker).ctx.compose('A prompt with no attachments at all here.');
    assert.strictEqual(withDocx.confidence, 'low', 'an unparsed container drags the whole total down');
  } finally { page.restore(); }
});

test('a context-window share is shown only when the window is documented', () => {
  const known = makeContext(CLAUDE).ctx.compose('Summarize the report for me please.');
  assert.strictEqual(known.contextTokens, 1000000);
  assert.ok(known.contextPercent > 0);

  // GPT-5.4 Thinking has no first-party ChatGPT context number, so no share.
  const unknown = makeContext({ provider: 'openai', canonicalModel: 'gpt-5.4-thinking', surface: 'chatgpt' })
    .ctx.compose('Summarize the report for me please.');
  assert.strictEqual(unknown.contextTokens, null);
  assert.strictEqual(unknown.contextPercent, null);

  // And Auto never gets one either: no model, no window.
  const auto = makeContext({ provider: 'openai', canonicalModel: null, routing: 'auto', surface: 'chatgpt' })
    .ctx.compose('Summarize the report for me please.');
  assert.strictEqual(auto.contextPercent, null);
});

test('platform overhead is named, never numbered', () => {
  const b = makeContext(CLAUDE).ctx.compose('Summarize the report for me please.');
  assert.ok(b.unmeasured.length >= 4);
  assert.ok(b.unmeasured.some((s) => /system prompt/i.test(s)));
  assert.ok(b.unmeasured.some((s) => /reasoning tokens/i.test(s)));
  // Nothing in the total came from that list.
  assert.strictEqual(b.total, b.parts.reduce((n, p) => n + p.tokens, 0));
});
